console.log(process);

// output: 
/*
process {
  version: 'v23.4.0',
  versions: {
    node: '23.4.0',
    acorn: '8.14.0',
    ada: '2.9.2',
    amaro: '0.2.0',
    ares: '1.34.3',
    brotli: '1.1.0',
    cjs_module_lexer: '1.4.1',
    cldr: '46.0',
    icu: '76.1',
    llhttp: '9.2.1',
    modules: '131',
    napi: '9',
    nbytes: '0.1.1',
    ncrypto: '0.0.1',
    nghttp2: '1.64.0',
    nghttp3: '0.7.0',
    ngtcp2: '1.9.1',
    openssl: '3.0.15+quic',
    simdjson: '3.10.1',
    simdutf: '5.6.3',
    sqlite: '3.47.1',
    tz: '2024b',
    undici: '6.21.0',
    unicode: '16.0',
    uv: '1.49.1',
    uvwasi: '0.0.21',
    v8: '12.9.202.28-node.11',
    zlib: '1.3.0.1-motley-82a5fec'
  },
  arch: 'x64',
  platform: 'win32',
  release: {
    name: 'node',
    sourceUrl: 'https://nodejs.org/download/release/v23.4.0/node-v23.4.0.tar.gz',        
    headersUrl: 'https://nodejs.org/download/release/v23.4.0/node-v23.4.0-headers.tar.gz',
    libUrl: 'https://nodejs.org/download/release/v23.4.0/win-x64/node.lib'
  },
  _rawDebug: [Function: _rawDebug],
  moduleLoadList: [
    'Internal Binding builtins',
    'Internal Binding module_wrap',
    'Internal Binding errors',
    'NativeModule internal/assert',
    'Internal Binding util',
    'NativeModule internal/errors',
    'Internal Binding config',
    'Internal Binding timers',
    'Internal Binding async_wrap',
    'Internal Binding task_queue',
    'Internal Binding symbols',
    'NativeModule internal/async_hooks',
    'Internal Binding constants',
    'Internal Binding types',
    'Internal Binding options',
    'NativeModule internal/options',
    'Internal Binding string_decoder',
    'NativeModule internal/util',
    'NativeModule internal/util/types',
    'NativeModule internal/validators',
    'NativeModule internal/linkedlist',
    'NativeModule internal/priority_queue',
    'Internal Binding icu',
    'NativeModule internal/util/inspect',
    'NativeModule internal/constants',
    'Internal Binding trace_events',
    'NativeModule internal/util/debuglog',
    'Internal Binding async_context_frame',
    'NativeModule internal/async_context_frame',
    'NativeModule internal/timers',
    'NativeModule internal/events/abort_listener',
    'NativeModule events',
    'Internal Binding buffer',
    'NativeModule internal/buffer',
    'NativeModule buffer',
    'NativeModule internal/webidl',
    'Internal Binding messaging',
    'NativeModule internal/worker/js_transferable',
    'Internal Binding process_methods',
    'NativeModule internal/process/per_thread',
    'Internal Binding credentials',
    'NativeModule internal/process/promises',
    'NativeModule internal/fixed_queue',
    'NativeModule async_hooks',
    'NativeModule internal/process/task_queues',
    'NativeModule timers',
    'NativeModule path',
    'NativeModule internal/querystring',
    'NativeModule querystring',
    'Internal Binding url',
    'NativeModule internal/url',
    'Internal Binding contextify',
    'NativeModule internal/vm',
    'NativeModule internal/process/execution',
    'NativeModule internal/process/warning',
    'NativeModule internal/source_map/source_map_cache',
    'Internal Binding fs',
    'Internal Binding blob',
    'Internal Binding encoding_binding',
    'NativeModule internal/encoding',
    'NativeModule internal/streams/utils',
    'NativeModule util',
    'NativeModule internal/webstreams/util',
    'NativeModule internal/webstreams/queuingstrategies',
    'NativeModule internal/blob',
    'NativeModule internal/fs/utils',
    'Internal Binding permission',
    'NativeModule internal/process/permission',
    'NativeModule fs',
    'Internal Binding modules',
    'NativeModule internal/modules/helpers',
    'NativeModule internal/console/constructor',
    'NativeModule internal/console/global',
    'NativeModule internal/util/inspector',
    'Internal Binding inspector',
    'Internal Binding performance',
    'NativeModule internal/perf/utils',
    'NativeModule internal/event_target',
    'Internal Binding wasm_web_api',
    'Internal Binding mksnapshot',
    'NativeModule internal/v8/startup_snapshot',
    'NativeModule internal/process/signal',
    'NativeModule url',
    'NativeModule internal/modules/typescript',
    'NativeModule internal/modules/package_json_reader',
    'NativeModule diagnostics_channel',
    'NativeModule internal/modules/cjs/loader',
    'NativeModule internal/process/pre_execution',
    'NativeModule internal/modules/esm/utils',
    'NativeModule internal/inspector_async_hook',
    'Internal Binding worker',
    'NativeModule internal/modules/run_main',
    'NativeModule internal/net',
    'NativeModule internal/dns/utils',
    'NativeModule vm',
    'NativeModule internal/abort_controller',
    'NativeModule internal/streams/end-of-stream',
    'NativeModule internal/streams/destroy',
    'NativeModule internal/streams/legacy',
    'NativeModule internal/streams/add-abort-signal',
    ... 30 more items
  ],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events: [Object: null prototype] {
    newListener: [ [Function (anonymous)], [Function: startListeningIfSignal] ],
    removeListener: [ [Function (anonymous)], [Function: stopListeningIfSignal] ],       
    warning: [Function: onWarning],
    SIGWINCH: [
      [Function: refreshStdoutOnSigWinch],
      [Function: refreshStderrOnSigWinch]
    ]
  },
  _eventsCount: 4,
  _maxListeners: undefined,
  domain: null,
  _exiting: [Getter/Setter],
  exitCode: [Getter/Setter],
  config: {
    target_defaults: {
      cflags: [],
      configurations: [Object],
      default_configuration: 'Release',
      defines: [Array],
      include_dirs: [],
      libraries: []
    },
    variables: {
      asan: 0,
      clang: 0,
      coverage: false,
      dcheck_always_on: 0,
      debug_nghttp2: false,
      debug_node: false,
      enable_lto: false,
      enable_pgo_generate: false,
      enable_pgo_use: false,
      error_on_warn: false,
      force_dynamic_crt: 0,
      host_arch: 'x64',
      icu_data_in: '..\\..\\deps\\icu-tmp\\icudt76l.dat',
      icu_endianness: 'l',
      icu_gyp_path: 'tools/icu/icu-generic.gyp',
      icu_path: 'deps/icu-small',
      icu_small: false,
      icu_ver_major: '76',
      libdir: 'lib',
      llvm_version: '0.0',
      napi_build_version: '9',
      nasm_version: '2.16',
      node_builtin_shareable_builtins: [Array],
      node_byteorder: 'little',
      node_debug_lib: false,
      node_enable_d8: false,
      node_enable_v8_vtunejit: false,
      node_fipsinstall: false,
      node_install_corepack: true,
      node_install_npm: true,
      node_library_files: [Array],
      node_module_version: 131,
      node_no_browser_globals: false,
      node_prefix: '\\usr\\local',
      node_release_urlbase: 'https://nodejs.org/download/release/',
      node_shared: false,
      node_shared_ada: false,
      node_shared_brotli: false,
      node_shared_cares: false,
      node_shared_http_parser: false,
      node_shared_libuv: false,
      node_shared_nghttp2: false,
      node_shared_nghttp3: false,
      node_shared_ngtcp2: false,
      node_shared_openssl: false,
      node_shared_simdjson: false,
      node_shared_simdutf: false,
      node_shared_sqlite: false,
      node_shared_uvwasi: false,
      node_shared_zlib: false,
      node_tag: '',
      node_target_type: 'executable',
      node_use_amaro: true,
      node_use_bundled_v8: true,
      node_use_node_code_cache: true,
      node_use_node_snapshot: true,
      node_use_openssl: true,
      node_use_v8_platform: true,
      node_with_ltcg: true,
      node_without_node_options: false,
      node_write_snapshot_as_array_literals: true,
      openssl_is_fips: false,
      openssl_quic: true,
      ossfuzz: false,
      shlib_suffix: 'so.131',
      single_executable_application: true,
      target_arch: 'x64',
      ubsan: 0,
      use_prefix_to_find_headers: false,
      v8_enable_31bit_smis_on_64bit_arch: 0,
      v8_enable_extensible_ro_snapshot: 0,
      v8_enable_gdbjit: 0,
      v8_enable_hugepage: 0,
      v8_enable_i18n_support: 1,
      v8_enable_inspector: 1,
      v8_enable_javascript_promise_hooks: 1,
      v8_enable_lite_mode: 0,
      v8_enable_maglev: 1,
      v8_enable_object_print: 1,
      v8_enable_pointer_compression: 0,
      v8_enable_sandbox: 0,
      v8_enable_shared_ro_heap: 1,
      v8_enable_short_builtin_calls: 1,
      v8_enable_webassembly: 1,
      v8_optimized_debug: 1,
      v8_promise_internal_field_count: 1,
      v8_random_seed: 0,
      v8_trace_maps: 0,
      v8_use_siphash: 1,
      want_separate_host_toolset: 0
    }
  },
  dlopen: [Function: dlopen],
  uptime: [Function: uptime],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  getActiveResourcesInfo: [Function: getActiveResourcesInfo],
  reallyExit: [Function: reallyExit],
  _kill: [Function: _kill],
  loadEnvFile: [Function: loadEnvFile],
  cpuUsage: [Function: cpuUsage],
  resourceUsage: [Function: resourceUsage],
  memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
  constrainedMemory: [Function: constrainedMemory],
  availableMemory: [Function: availableMemory],
  kill: [Function: kill],
  exit: [Function: exit],
  finalization: [Getter/Setter],
  hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
  openStdin: [Function (anonymous)],
  allowedNodeEnvironmentFlags: [Getter/Setter],
  features: {
    inspector: true,
    debug: false,
    uv: true,
    ipv6: true,
    tls_alpn: true,
    tls_sni: true,
    tls_ocsp: true,
    tls: true,
    cached_builtins: [Getter],
    require_module: [Getter],
    typescript: [Getter]
  },
  _fatalException: [Function (anonymous)],
  setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback],  
  hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],  
  emitWarning: [Function: emitWarning],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: runNextTicks],
  sourceMapsEnabled: [Getter],
  setSourceMapsEnabled: [Function: setSourceMapsEnabled],
  getBuiltinModule: [Function: getBuiltinModule],
  _debugProcess: [Function: _debugProcess],
  _debugEnd: [Function: _debugEnd],
  _startProfilerIdleNotifier: [Function (anonymous)],
  _stopProfilerIdleNotifier: [Function (anonymous)],
  stdout: [Getter],
  stdin: [Getter],
  stderr: [Getter],
  abort: [Function: abort],
  umask: [Function: wrappedUmask],
  chdir: [Function: wrappedChdir],
  cwd: [Function: wrappedCwd],
  env: {
    ALLUSERSPROFILE: 'C:\\ProgramData',
    APPDATA: 'C:\\Users\\Harshan A\\AppData\\Roaming',
    CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\crashpad_9200_ZHGMRXTFPHFORYLD',
    CommonProgramFiles: 'C:\\Program Files\\Common Files',
    'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
    CommonProgramW6432: 'C:\\Program Files\\Common Files',
    COMPUTERNAME: 'DESKTOP-MAA0FAQ',
    ComSpec: 'C:\\WINDOWS\\system32\\cmd.exe',
    DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
    HOMEDRIVE: 'C:',
    HOMEPATH: '\\Users\\Harshan A',
    LOCALAPPDATA: 'C:\\Users\\Harshan A\\AppData\\Local',
    LOGONSERVER: '\\\\DESKTOP-MAA0FAQ',
    NUMBER_OF_PROCESSORS: '4',
    OneDrive: 'C:\\Users\\Harshan A\\OneDrive',
    OneDriveConsumer: 'C:\\Users\\Harshan A\\OneDrive',
    ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
    OS: 'Windows_NT',
    Path: 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Users\\Harshan A\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\Harshan A\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\Harshan A\\AppData\\Local\\GitHubDesktop\\bin;C:\\Users\\Harshan A\\AppData\\Roaming\\npm',    PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
    PROCESSOR_ARCHITECTURE: 'AMD64',
    PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 55 Stepping 3, GenuineIntel',
    PROCESSOR_LEVEL: '6',
    PROCESSOR_REVISION: '3703',
    ProgramData: 'C:\\ProgramData',
    ProgramFiles: 'C:\\Program Files',
    'ProgramFiles(x86)': 'C:\\Program Files (x86)',
    ProgramW6432: 'C:\\Program Files',
    PSModulePath: 'C:\\Users\\Harshan A\\OneDrive\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules',
    PUBLIC: 'C:\\Users\\Public',
    SESSIONNAME: 'Console',
    SystemDrive: 'C:',
    SystemRoot: 'C:\\WINDOWS',
    TEMP: 'C:\\Users\\HARSHA~1\\AppData\\Local\\Temp',
    TMP: 'C:\\Users\\HARSHA~1\\AppData\\Local\\Temp',
    USERDOMAIN: 'DESKTOP-MAA0FAQ',
    USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-MAA0FAQ',
    USERNAME: 'Harshan A',
    USERPROFILE: 'C:\\Users\\Harshan A',
    windir: 'C:\\WINDOWS',
    TERM_PROGRAM: 'vscode',
    TERM_PROGRAM_VERSION: '1.94.2',
    LANG: 'en_US.UTF-8',
    COLORTERM: 'truecolor',
    GIT_ASKPASS: 'c:\\Users\\Harshan A\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh',
    VSCODE_GIT_ASKPASS_NODE: 'C:\\Users\\Harshan A\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe',
    VSCODE_GIT_ASKPASS_EXTRA_ARGS: '',
    VSCODE_GIT_ASKPASS_MAIN: 'c:\\Users\\Harshan A\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js',
    VSCODE_GIT_IPC_HANDLE: '\\\\.\\pipe\\vscode-git-8e8f70e034-sock',
    VSCODE_INJECTION: '1',
    VSCODE_NONCE: '3c8b436a-e7ae-436c-ab60-4a99b9396afd',
    VSCODE_STABLE: '1'
  },
  title: 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
  argv: [
    'C:\\Program Files\\nodejs\\node.exe',
    'C:\\Mine\\node-js\\2-globals\\process'
  ],
  execArgv: [],
  pid: 6808,
  ppid: 1372,
  execPath: 'C:\\Program Files\\nodejs\\node.exe',
  debugPort: 9229,
  argv0: 'C:\\Program Files\\nodejs\\node.exe',
  _preload_modules: [],
  report: [Getter],
  mainModule: {
    id: '.',
    path: 'C:\\Mine\\node-js\\2-globals',
    exports: {},
    filename: 'C:\\Mine\\node-js\\2-globals\\process.js',
    loaded: false,
    children: [],
    paths: [
      'C:\\Mine\\node-js\\2-globals\\node_modules',
      'C:\\Mine\\node-js\\node_modules',
      'C:\\Mine\\node_modules',
      'C:\\node_modules'
    ],
    [Symbol(kIsMainSymbol)]: true,
    [Symbol(kIsCachedByESMLoader)]: false,
    [Symbol(kIsExecuting)]: true
  },
  [Symbol(shapeMode)]: false,
  [Symbol(kCapture)]: false
}
*/